import { Router } from 'express';
import authRoutes from './auth.routes';
import employeeRoutes from './employees.routes';
import clientRoutes from './clients.routes';
import assignmentRoutes from './assignments.routes';
import timesheetRoutes from './timesheets.routes';
import monthlyTimesheetRoutes from './monthlyTimesheets.routes';
import leaveRequestRoutes from './leaveRequests.routes';
import invoiceRoutes from './invoices.routes';
import productRoutes from './products.routes';
import recurringRoutes from './recurring.routes';
import publicRoutes from './public.routes';
import reportRoutes from './reports.routes';
import documentRoutes from './documents.routes';
import notificationRoutes from './notifications.routes';
import adminRoutes from './admin.routes';
import systemRoutes from './system.routes';

export const router = Router();

router.use('/auth', authRoutes);
router.use('/employees', employeeRoutes);
router.use('/clients', clientRoutes);
router.use('/assignments', assignmentRoutes);
router.use('/timesheets', timesheetRoutes);
router.use('/monthly-timesheets', monthlyTimesheetRoutes);
router.use('/leave-requests', leaveRequestRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/products', productRoutes);
router.use('/recurring-invoices', recurringRoutes);
router.use('/public', publicRoutes);
router.use('/reports', reportRoutes);
router.use('/documents', documentRoutes);
router.use('/notifications', notificationRoutes);
router.use('/admin', adminRoutes);
router.use('/system', systemRoutes);
