import { Router } from 'express';
import authRoutes from './auth.routes';
import employeeRoutes from './employees.routes';
import clientRoutes from './clients.routes';
import assignmentRoutes from './assignments.routes';
import timesheetRoutes from './timesheets.routes';
import monthlyTimesheetRoutes from './monthlyTimesheets.routes';
import leaveRequestRoutes from './leaveRequests.routes';
import invoiceRoutes from './invoices.routes';

import publicRoutes from './public.routes';
import reportRoutes from './reports.routes';
import documentRoutes from './documents.routes';
import notificationRoutes from './notifications.routes';
import adminRoutes from './admin.routes';
import systemRoutes from './system.routes';
import emailTemplateRoutes from './emailTemplates.routes';
import invoiceTemplateRoutes from './invoiceTemplates.routes';
import announcementRoutes from './announcements.routes';
import leaveBalanceRoutes from './leaveBalance.routes';
import expenseRoutes from './expenses.routes';
import onboardingChecklistRoutes from './onboardingChecklist.routes';
import assetRoutes from './assets.routes';
import reviewRoutes from './reviews.routes';
import holidayRoutes from './holidays.routes';
import settingsRoutes from './settings.routes';
import offboardingRoutes from './offboarding.routes';
import skillsRoutes from './skills.routes';
import shiftsRoutes from './shifts.routes';
import budgetsRoutes from './budgets.routes';
import taxDocumentsRoutes from './taxDocuments.routes';
import activityLogsRoutes from './activityLogs.routes';
import analyticsReportsRoutes from './analyticsReports.routes';
import navBadgesRoutes from './navBadges.routes';

export const router = Router();

router.use('/auth', authRoutes);
router.use('/employees', employeeRoutes);
router.use('/clients', clientRoutes);
router.use('/assignments', assignmentRoutes);
router.use('/timesheets', timesheetRoutes);
router.use('/monthly-timesheets', monthlyTimesheetRoutes);
router.use('/leave-requests', leaveRequestRoutes);
router.use('/invoices', invoiceRoutes);

router.use('/public', publicRoutes);
router.use('/reports', reportRoutes);
router.use('/documents', documentRoutes);
router.use('/notifications', notificationRoutes);
router.use('/admin', adminRoutes);
router.use('/system', systemRoutes);
router.use('/email-templates', emailTemplateRoutes);
router.use('/invoice-templates', invoiceTemplateRoutes);
router.use('/announcements', announcementRoutes);
router.use('/leave', leaveBalanceRoutes);
router.use('/expenses', expenseRoutes);
router.use('/onboarding-checklist', onboardingChecklistRoutes);
router.use('/assets', assetRoutes);
router.use('/reviews', reviewRoutes);
router.use('/holidays', holidayRoutes);
router.use('/portal-settings', settingsRoutes);
router.use('/offboarding-checklist', offboardingRoutes);
router.use('/skills', skillsRoutes);
router.use('/shifts', shiftsRoutes);
router.use('/budgets', budgetsRoutes);
router.use('/tax-documents', taxDocumentsRoutes);
router.use('/activity-logs', activityLogsRoutes);
router.use('/analytics', analyticsReportsRoutes);
router.use('/nav-badges', navBadgesRoutes);
